In [1]:
import numpy as np

In [2]:
arr2= np.array([[1,13,14,1],[5,1,1,8]])
arr2

array([[ 1, 13, 14,  1],
       [ 5,  1,  1,  8]])

In [19]:
arr3=arr2-2*3*5
print(arr3)
arr3==arr2

[[-29 -17 -16 -29]
 [-25 -29 -29 -22]]


array([[False, False, False, False],
       [False, False, False, False]])

In [7]:
a=np.ones(12)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
b=np.arange(1,101).reshape(10,10)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [9]:
c=np.extract([b%2==0],b)
c

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [10]:
b[b%2==0]= False

In [11]:
b

array([[ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0],
       [11,  0, 13,  0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27,  0, 29,  0],
       [31,  0, 33,  0, 35,  0, 37,  0, 39,  0],
       [41,  0, 43,  0, 45,  0, 47,  0, 49,  0],
       [51,  0, 53,  0, 55,  0, 57,  0, 59,  0],
       [61,  0, 63,  0, 65,  0, 67,  0, 69,  0],
       [71,  0, 73,  0, 75,  0, 77,  0, 79,  0],
       [81,  0, 83,  0, 85,  0, 87,  0, 89,  0],
       [91,  0, 93,  0, 95,  0, 97,  0, 99,  0]])

In [12]:
b[b%2==0].reshape(5,10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
f=[b%2==0]
f

[array([[False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True],
        [False,  True, False,  True, False,  True, False,  True, False,
          True]])]

In [14]:
b[b>50]

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

In [15]:
b[5]

array([51,  0, 53,  0, 55,  0, 57,  0, 59,  0])

In [16]:
b[5][5]

0

In [17]:
b[1:10:2, 1:10:1]

array([[ 0, 13,  0, 15,  0, 17,  0, 19,  0],
       [ 0, 33,  0, 35,  0, 37,  0, 39,  0],
       [ 0, 53,  0, 55,  0, 57,  0, 59,  0],
       [ 0, 73,  0, 75,  0, 77,  0, 79,  0],
       [ 0, 93,  0, 95,  0, 97,  0, 99,  0]])

In [18]:
a1=np.ones(40).reshape(8,5)
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
a1[1:-1, 1:-1]=0
a1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
a1[1:-1, 1:-1]=0
a1.reshape(8,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
a1=np.arange(10,35).reshape(5,5)
a1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [22]:
a1.squeeze(axis=None)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [23]:
a1=np.sqrt(a1)
a1

array([[3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189]])

In [24]:
a1=np.power(a1,4)
a1

array([[ 100.,  121.,  144.,  169.,  196.],
       [ 225.,  256.,  289.,  324.,  361.],
       [ 400.,  441.,  484.,  529.,  576.],
       [ 625.,  676.,  729.,  784.,  841.],
       [ 900.,  961., 1024., 1089., 1156.]])

In [25]:
salary= np.array([1,-2,25000,45000,9,10000])
salary

array([    1,    -2, 25000, 45000,     9, 10000])

In [26]:
np.where(salary<=10, False,"")

array(['False', 'False', '', '', 'False', ''], dtype='<U5')

In [27]:
salary= np.array([0,-2,25000,45000,9,10000])
salary

array([    0,    -2, 25000, 45000,     9, 10000])

In [28]:
salary.sum()

80007

In [29]:
salary.cumsum()

array([    0,    -2, 24998, 69998, 70007, 80007])

In [30]:
salary.all()

False

In [31]:
salary.cumprod()

array([0, 0, 0, 0, 0, 0])

In [32]:
y=salary>6
y

array([False, False,  True,  True,  True,  True])

In [33]:
y.sum()

4

In [34]:
salary.sort()
salary

array([   -2,     0,     9, 10000, 25000, 45000])

In [35]:
np.unique(salary)

array([   -2,     0,     9, 10000, 25000, 45000])

In [36]:
x=[1,2,3,4,5] 
y=[6,7,8,9,10]

In [37]:
save=np.save('textx.npy',x)
print(save)

None


In [38]:
loadx=np.load('textx.npy')
loadx

array([1, 2, 3, 4, 5])

In [39]:
save=np.savez('textxy.npy',x,y)
print(save)

None


In [40]:
loadxy=np.load('textyz.npz')

FileNotFoundError: [Errno 2] No such file or directory: 'textyz.npz'

In [41]:
loadxy=np.load('textx.npy')

In [42]:
loadxy

array([1, 2, 3, 4, 5])

In [43]:
np.random.seed(7)

In [46]:
np.random.normal(size=(3,3))

array([[-4.65937371e-01,  3.28201637e-02,  4.07516283e-01],
       [-7.88923029e-01,  2.06557291e-03, -8.90385858e-04],
       [-1.75472431e+00,  1.01765801e+00,  6.00498516e-01]])

In [47]:
np.random.uniform(size=(3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])

In [49]:
x=([1,3,5],[7,9,0])
arr1=np.array(x)
arr1

array([[1, 3, 5],
       [7, 9, 0]])

In [50]:
y=([11,13,15],[17,19,10])
arr2=np.array(y)
arr2

array([[11, 13, 15],
       [17, 19, 10]])

In [52]:
con=np.concatenate((arr1,arr2),axis=0)
con

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [53]:
con=np.concatenate((arr1,arr2),axis=1)
con

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [55]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [56]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [57]:
aa= np.array([1,2,3,4,5,6,7,8,9,10])
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
np.split(aa, (4,6))

[array([1, 2, 3, 4]), array([5, 6]), array([ 7,  8,  9, 10])]

In [69]:
np.split(aa, (4,7))

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [88]:
x=[[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18]]
x

[[1, 2, 3, 4, 5, 6, 7, 8], [11, 12, 13, 14, 15, 16, 17, 18]]

In [75]:
d=np.array(x)

In [86]:
np.split(d,[4,6],axis=1)

[array([[ 1,  2,  3,  4],
        [11, 12, 13, 14]]),
 array([[ 5,  6],
        [15, 16]]),
 array([[ 7,  8],
        [17, 18]])]

In [87]:
np.split(d,[1],axis=1)

[array([[ 1],
        [11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8],
        [12, 13, 14, 15, 16, 17, 18]])]

In [12]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
a1=np.repeat(a,2)
a1

array([1, 1, 2, 2, 3, 3])

In [14]:
a2=np.tile(a,3)
a2

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
a3=np.hstack((a.repeat(3), np.tile(a,3)))
a3

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
a3=np.hstack((a1,a2))
a3

array([1, 1, 2, 2, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])